export const allowedFileTypes = [
  "jpg",
  "jpeg",
  "png",
  "stl",
  "mp4",
  "iiwgl",
  "pdf",
  "csv",
  "xls",
  "xlsx",
  "doc",
  "docx",
  "prg",
  "pts",
  "zip",
  "rar",
];

export const allowedMimeTypes = [
  "image/jpeg",
  "image/png",
  "model/stl",
  "video/mp4",
  "application/pdf",
  "text/csv",
  "application/vnd.rar",
  "application/vnd.ms-pki.stl",
  "application/vnd.ms-excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/x-rar-compressed",
  "application/x-compressed",
  "application/x-zip-compressed",
  "application/zip",
  "multipart/x-zip",
  "application/octet-stream",
];

export const maxFileSize = 64 * 1024 * 1024; // mb * 1024 * 1024 bytes
